name: Build AppDrawer
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang lld dpkg wget perl xz-utils
          git clone --recurse-submodules https://github.com/theos/theos.git ~/.theos
          chmod +x ~/.theos/bin/dm.pl
          echo "THEOS=~/.theos" >> $GITHUB_ENV
          echo "PATH=~/.theos/bin:$PATH" >> $GITHUB_ENV
      - name: Install iOS SDK
        run: |
          mkdir -p ~/.theos/sdks
          cd ~/.theos/sdks
          wget -q "https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS16.5.sdk.tar.xz"
          tar -xf iPhoneOS16.5.sdk.tar.xz
          rm iPhoneOS16.5.sdk.tar.xz
          ls -la
      - name: Install toolchain
        run: |
          ~/.theos/bin/install-toolchain
